// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StardewGroupProject.Data;

#nullable disable

namespace StardewGroupProject.Migrations
{
    [DbContext(typeof(FarmContext))]
    [Migration("20240802201039_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StardewGroupProject.Models.Bundle", b =>
                {
                    b.Property<int>("BundleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BundleId"));

                    b.Property<bool>("Complete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("BundleId");

                    b.HasIndex("RoomId");

                    b.ToTable("Bundles");
                });

            modelBuilder.Entity("StardewGroupProject.Models.Farm", b =>
                {
                    b.Property<int>("FarmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FarmId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FarmId");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("StardewGroupProject.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int?>("BundleId")
                        .HasColumnType("int");

                    b.Property<bool>("Complete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.HasIndex("BundleId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("StardewGroupProject.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<int?>("FarmId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomId");

                    b.HasIndex("FarmId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("StardewGroupProject.Models.Bundle", b =>
                {
                    b.HasOne("StardewGroupProject.Models.Room", null)
                        .WithMany("Bundles")
                        .HasForeignKey("RoomId");
                });

            modelBuilder.Entity("StardewGroupProject.Models.Item", b =>
                {
                    b.HasOne("StardewGroupProject.Models.Bundle", null)
                        .WithMany("Items")
                        .HasForeignKey("BundleId");
                });

            modelBuilder.Entity("StardewGroupProject.Models.Room", b =>
                {
                    b.HasOne("StardewGroupProject.Models.Farm", null)
                        .WithMany("Rooms")
                        .HasForeignKey("FarmId");
                });

            modelBuilder.Entity("StardewGroupProject.Models.Bundle", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("StardewGroupProject.Models.Farm", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("StardewGroupProject.Models.Room", b =>
                {
                    b.Navigation("Bundles");
                });
#pragma warning restore 612, 618
        }
    }
}
